# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'abm.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(906, 584)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitulo = QtWidgets.QLabel(Dialog)
        self.lblTitulo.setObjectName("lblTitulo")
        self.verticalLayout.addWidget(self.lblTitulo)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabLista = QtWidgets.QWidget()
        self.tabLista.setObjectName("tabLista")
        self.gridLayout = QtWidgets.QGridLayout(self.tabLista)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditBusqueda = QtWidgets.QLineEdit(self.tabLista)
        self.lineEditBusqueda.setObjectName("lineEditBusqueda")
        self.gridLayout.addWidget(self.lineEditBusqueda, 0, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.tabLista)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAgregar = QtWidgets.QPushButton(self.tabLista)
        self.btnAgregar.setObjectName("btnAgregar")
        self.horizontalLayout.addWidget(self.btnAgregar)
        self.btnEditar = QtWidgets.QPushButton(self.tabLista)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imagenes/modificar.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btnEditar.setIcon(icon)
        self.btnEditar.setObjectName("btnEditar")
        self.horizontalLayout.addWidget(self.btnEditar)
        self.btnBorrar = QtWidgets.QPushButton(self.tabLista)
        self.btnBorrar.setObjectName("btnBorrar")
        self.horizontalLayout.addWidget(self.btnBorrar)
        self.btnCerrar = QtWidgets.QPushButton(self.tabLista)
        self.btnCerrar.setObjectName("btnCerrar")
        self.horizontalLayout.addWidget(self.btnCerrar)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabLista, "")
        self.tabDetalle = QtWidgets.QWidget()
        self.tabDetalle.setObjectName("tabDetalle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabDetalle)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.grdDatos = QtWidgets.QGridLayout()
        self.grdDatos.setObjectName("grdDatos")
        self.label = QtWidgets.QLabel(self.tabDetalle)
        self.label.setObjectName("label")
        self.grdDatos.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tabDetalle)
        self.lineEdit.setObjectName("lineEdit")
        self.grdDatos.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.grdDatos)
        self.grdBotones = QtWidgets.QGridLayout()
        self.grdBotones.setObjectName("grdBotones")
        self.btnAceptar = QtWidgets.QPushButton(self.tabDetalle)
        self.btnAceptar.setObjectName("btnAceptar")
        self.grdBotones.addWidget(self.btnAceptar, 0, 0, 1, 1)
        self.btnCancelar = QtWidgets.QPushButton(self.tabDetalle)
        self.btnCancelar.setObjectName("btnCancelar")
        self.grdBotones.addWidget(self.btnCancelar, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.grdBotones)
        self.tabWidget.addTab(self.tabDetalle, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditBusqueda, self.btnEditar)
        Dialog.setTabOrder(self.btnEditar, self.btnBorrar)
        Dialog.setTabOrder(self.btnBorrar, self.btnCerrar)
        Dialog.setTabOrder(self.btnCerrar, self.tableView)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblTitulo.setText(_translate("Dialog", "TextLabel"))
        self.btnAgregar.setText(_translate("Dialog", "Agregar"))
        self.btnEditar.setText(_translate("Dialog", "&Editar"))
        self.btnBorrar.setText(_translate("Dialog", "Borrar"))
        self.btnCerrar.setText(_translate("Dialog", "Cerrar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLista), _translate("Dialog", "Tab 1"))
        self.tabDetalle.setToolTip(_translate("Dialog", "Detalle de datos"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.btnAceptar.setText(_translate("Dialog", "&Aceptar"))
        self.btnCancelar.setText(_translate("Dialog", "&Cancelar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDetalle), _translate("Dialog", "Tab 2"))

