# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'carga_cliente_venta.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgCliente(object):
    def setupUi(self, dlgCliente):
        dlgCliente.setObjectName("dlgCliente")
        dlgCliente.resize(771, 244)
        self.horizontalLayout = QtWidgets.QHBoxLayout(dlgCliente)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitulo = QtWidgets.QLabel(dlgCliente)
        self.lblTitulo.setObjectName("lblTitulo")
        self.verticalLayout.addWidget(self.lblTitulo)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblCboFormaPago = QtWidgets.QLabel(dlgCliente)
        self.lblCboFormaPago.setObjectName("lblCboFormaPago")
        self.gridLayout.addWidget(self.lblCboFormaPago, 5, 0, 1, 1)
        self.lineDomicilio = QtWidgets.QLineEdit(dlgCliente)
        self.lineDomicilio.setObjectName("lineDomicilio")
        self.gridLayout.addWidget(self.lineDomicilio, 2, 2, 1, 1)
        self.cboFormaPago = QtWidgets.QComboBox(dlgCliente)
        self.cboFormaPago.setObjectName("cboFormaPago")
        self.gridLayout.addWidget(self.cboFormaPago, 5, 2, 1, 1)
        self.lblCuotaTarjeta = QtWidgets.QLabel(dlgCliente)
        self.lblCuotaTarjeta.setObjectName("lblCuotaTarjeta")
        self.gridLayout.addWidget(self.lblCuotaTarjeta, 6, 0, 1, 1)
        self.lineCuotaTarjeta = QtWidgets.QLineEdit(dlgCliente)
        self.lineCuotaTarjeta.setObjectName("lineCuotaTarjeta")
        self.gridLayout.addWidget(self.lineCuotaTarjeta, 6, 2, 1, 1)
        self.lblSitFteIVA = QtWidgets.QLabel(dlgCliente)
        self.lblSitFteIVA.setObjectName("lblSitFteIVA")
        self.gridLayout.addWidget(self.lblSitFteIVA, 3, 0, 1, 1)
        self.lineLimCredito = QtWidgets.QLineEdit(dlgCliente)
        self.lineLimCredito.setObjectName("lineLimCredito")
        self.gridLayout.addWidget(self.lineLimCredito, 4, 2, 1, 1)
        self.vldCliente = QtWidgets.QLineEdit(dlgCliente)
        self.vldCliente.setObjectName("vldCliente")
        self.gridLayout.addWidget(self.vldCliente, 0, 2, 1, 1)
        self.lblDomicilio = QtWidgets.QLabel(dlgCliente)
        self.lblDomicilio.setObjectName("lblDomicilio")
        self.gridLayout.addWidget(self.lblDomicilio, 2, 0, 1, 1)
        self.lineSitFteIVA = QtWidgets.QLineEdit(dlgCliente)
        self.lineSitFteIVA.setObjectName("lineSitFteIVA")
        self.gridLayout.addWidget(self.lineSitFteIVA, 3, 2, 1, 1)
        self.lblLimCred = QtWidgets.QLabel(dlgCliente)
        self.lblLimCred.setObjectName("lblLimCred")
        self.gridLayout.addWidget(self.lblLimCred, 4, 0, 1, 1)
        self.lblCliente = QtWidgets.QLabel(dlgCliente)
        self.lblCliente.setObjectName("lblCliente")
        self.gridLayout.addWidget(self.lblCliente, 0, 0, 1, 1)
        self.lblNombreCli = QtWidgets.QLabel(dlgCliente)
        self.lblNombreCli.setObjectName("lblNombreCli")
        self.gridLayout.addWidget(self.lblNombreCli, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.chkTicketFactura = QtWidgets.QCheckBox(dlgCliente)
        self.chkTicketFactura.setObjectName("chkTicketFactura")
        self.verticalLayout.addWidget(self.chkTicketFactura)
        self.pushButtonAceptar = QtWidgets.QPushButton(dlgCliente)
        self.pushButtonAceptar.setObjectName("pushButtonAceptar")
        self.verticalLayout.addWidget(self.pushButtonAceptar)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(dlgCliente)
        QtCore.QMetaObject.connectSlotsByName(dlgCliente)
        dlgCliente.setTabOrder(self.vldCliente, self.lineDomicilio)
        dlgCliente.setTabOrder(self.lineDomicilio, self.lineSitFteIVA)
        dlgCliente.setTabOrder(self.lineSitFteIVA, self.lineLimCredito)
        dlgCliente.setTabOrder(self.lineLimCredito, self.cboFormaPago)
        dlgCliente.setTabOrder(self.cboFormaPago, self.lineCuotaTarjeta)
        dlgCliente.setTabOrder(self.lineCuotaTarjeta, self.chkTicketFactura)
        dlgCliente.setTabOrder(self.chkTicketFactura, self.pushButtonAceptar)

    def retranslateUi(self, dlgCliente):
        _translate = QtCore.QCoreApplication.translate
        dlgCliente.setWindowTitle(_translate("dlgCliente", "Dialog"))
        self.lblTitulo.setText(_translate("dlgCliente", "TextLabel"))
        self.lblCboFormaPago.setText(_translate("dlgCliente", "TextLabel"))
        self.lblCuotaTarjeta.setText(_translate("dlgCliente", "TextLabel"))
        self.lblSitFteIVA.setText(_translate("dlgCliente", "TextLabel"))
        self.lblDomicilio.setText(_translate("dlgCliente", "TextLabel"))
        self.lblLimCred.setText(_translate("dlgCliente", "TextLabel"))
        self.lblCliente.setText(_translate("dlgCliente", "TextLabel"))
        self.lblNombreCli.setText(_translate("dlgCliente", "TextLabel"))
        self.chkTicketFactura.setText(_translate("dlgCliente", "CheckBox"))
        self.pushButtonAceptar.setText(_translate("dlgCliente", "PushButton"))

