# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venta.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(934, 642)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblTitulo = QtWidgets.QLabel(Dialog)
        self.lblTitulo.setObjectName("lblTitulo")
        self.gridLayout_4.addWidget(self.lblTitulo, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setObjectName("tableView")
        self.gridLayout_3.addWidget(self.tableView, 0, 0, 1, 1)
        self.lineEditCodBarra = QtWidgets.QLineEdit(Dialog)
        self.lineEditCodBarra.setObjectName("lineEditCodBarra")
        self.gridLayout_3.addWidget(self.lineEditCodBarra, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblPercepDGR = QtWidgets.QLabel(Dialog)
        self.lblPercepDGR.setObjectName("lblPercepDGR")
        self.gridLayout.addWidget(self.lblPercepDGR, 5, 1, 1, 1)
        self.lblIVA = QtWidgets.QLabel(Dialog)
        self.lblIVA.setObjectName("lblIVA")
        self.gridLayout.addWidget(self.lblIVA, 4, 1, 1, 1)
        self.lblSubtotal = QtWidgets.QLabel(Dialog)
        self.lblSubtotal.setObjectName("lblSubtotal")
        self.gridLayout.addWidget(self.lblSubtotal, 3, 1, 1, 1)
        self.lineEditTotal = QtWidgets.QLineEdit(Dialog)
        self.lineEditTotal.setObjectName("lineEditTotal")
        self.gridLayout.addWidget(self.lineEditTotal, 6, 2, 1, 1)
        self.lblFecha = QtWidgets.QLabel(Dialog)
        self.lblFecha.setObjectName("lblFecha")
        self.gridLayout.addWidget(self.lblFecha, 1, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 1, 1, 1, 2)
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 2, 0, 1, 3)
        self.lblTotal = QtWidgets.QLabel(Dialog)
        self.lblTotal.setObjectName("lblTotal")
        self.gridLayout.addWidget(self.lblTotal, 6, 1, 1, 1)
        self.btnSalir = QtWidgets.QPushButton(Dialog)
        self.btnSalir.setObjectName("btnSalir")
        self.gridLayout.addWidget(self.btnSalir, 0, 1, 1, 2)
        self.lineEditSubTotal = QtWidgets.QLineEdit(Dialog)
        self.lineEditSubTotal.setObjectName("lineEditSubTotal")
        self.gridLayout.addWidget(self.lineEditSubTotal, 3, 2, 1, 1)
        self.lineEditIVA = QtWidgets.QLineEdit(Dialog)
        self.lineEditIVA.setObjectName("lineEditIVA")
        self.gridLayout.addWidget(self.lineEditIVA, 4, 2, 1, 1)
        self.lineEditPercepDGR = QtWidgets.QLineEdit(Dialog)
        self.lineEditPercepDGR.setObjectName("lineEditPercepDGR")
        self.gridLayout.addWidget(self.lineEditPercepDGR, 5, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblCliente = QtWidgets.QLabel(Dialog)
        self.lblCliente.setObjectName("lblCliente")
        self.gridLayout_2.addWidget(self.lblCliente, 0, 0, 1, 1)
        self.lblInfo = QtWidgets.QLabel(Dialog)
        self.lblInfo.setObjectName("lblInfo")
        self.gridLayout_2.addWidget(self.lblInfo, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 2, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditCodBarra, self.tableView)
        Dialog.setTabOrder(self.tableView, self.dateEdit)
        Dialog.setTabOrder(self.dateEdit, self.graphicsView)
        Dialog.setTabOrder(self.graphicsView, self.lineEditTotal)
        Dialog.setTabOrder(self.lineEditTotal, self.btnSalir)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblTitulo.setText(_translate("Dialog", "TextLabel"))
        self.lblPercepDGR.setText(_translate("Dialog", "TextLabel"))
        self.lblIVA.setText(_translate("Dialog", "TextLabel"))
        self.lblSubtotal.setText(_translate("Dialog", "TextLabel"))
        self.lblFecha.setText(_translate("Dialog", "Fecha comprobante"))
        self.lblTotal.setText(_translate("Dialog", "Total"))
        self.btnSalir.setText(_translate("Dialog", "&Salir"))
        self.lblCliente.setText(_translate("Dialog", "TextLabel"))
        self.lblInfo.setText(_translate("Dialog", "TextLabel"))

